### PR TITLE
new changes

### PR DESCRIPTION
**Pull request by Ghasty003**
I added some animations to the "Correct" and "Game over" messages.
I also fixed some typo in the ReadMe file.

### CODE REVIEW

**Comment by na-cho-dev** [comment]
> I added some animations to the "Correct" and "Game over" messages. I also fixed some typo in the ReadMe file.
This is nice. I've actually been wanting to give it an update for a while now.

**Comment by Ghasty003** [comment]
> > I added some animations to the "Correct" and "Game over" messages. I also fixed some typo in the ReadMe file.
> > This is nice. I've actually been wanting to give it an update for a while now.

Thank you! Do well to accept the pull request and merge.

**Comment by na-cho-dev** [comment]
> 

Done. I'd love for us to connect.

**Comment by Ghasty003** [comment]
> > 
> 
> Done. I'd love for us to connect.

No problem :)
My social media handles are on my profile.

You can as well email your Whatsapp contact to me.

**Pull request merged**
